# Generated by Django 5.1.4 on 2025-01-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_project_parent_alter_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='recurrence',
            field=models.IntegerField(blank=True, choices=[(0, 'Every Day'), (1, 'Every Sunday'), (2, 'Every Monday'), (3, 'Every Tuesday'), (4, 'Every Wednesday'), (5, 'Every Thursday'), (6, 'Every Friday'), (7, 'Every Saturday')], null=True),
        ),
    ]
