# Generated by Django 5.1.4 on 2025-01-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_task_recurrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='recurrence',
            field=models.IntegerField(choices=[(-1, 'Never'), (0, 'Every Day'), (1, 'Every Sunday'), (2, 'Every Monday'), (3, 'Every Tuesday'), (4, 'Every Wednesday'), (5, 'Every Thursday'), (6, 'Every Friday'), (7, 'Every Saturday')], default=None),
            preserve_default=False,
        ),
    ]
