# Generated by Django 5.1.4 on 2025-01-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_task_recurrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinstance',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
