# Generated by Django 5.1.4 on 2025-01-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ident', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='full name'),
        ),
    ]
