# Generated by Django 5.1.4 on 2025-01-04 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_alter_task_due_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='sub_tasks_complete',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='sub_tasks_total',
            field=models.IntegerField(default=0),
        ),
    ]
