POST http://127.0.0.1:8000/api/account/login/ HTTP/1.1
content-type: application/json

{
    "email": "johndoe@example.com",
    "password": "ABC123!xyz"
}

###

POST http://127.0.0.1:8000/api/account/login/verify/ HTTP/1.1
content-type: application/json

{
    "token": ""
}

###

POST http://127.0.0.1:8000/api/account/login/renew/ HTTP/1.1
content-type: application/json

{
    "refresh": ""
}

###

POST http://127.0.0.1:8000/api/account/logout/ HTTP/1.1
content-type: application/json

{
    "refresh": ""
}

###

POST http://127.0.0.1:8000/api/account/signup/ HTTP/1.1
content-type: application/json

{
    "first_name": "John",
    "last_name": "Doe",
    "email": "johndoe@example.com",
    "password1": "ABC123!xyz",
    "password2": "ABC123!xyz"
}

###

POST http://127.0.0.1:8000/api/account/update/personal_info/ HTTP/1.1
content-type: application/json
Authorization: Bearer

{
    "first_name": "Jane",
    "last_name": "Doe"
}

###

POST http://127.0.0.1:8000/api/account/update/email/ HTTP/1.1
content-type: application/json
Authorization: Bearer

{
    "current_password": "ABC123!xyz",
    "email": "janedoe@example.com"
}

###

POST http://127.0.0.1:8000/api/account/update/password/ HTTP/1.1
content-type: application/json
Authorization: Bearer

{
    "current_password": "ABC123!xyz",
    "new_password1": "abc123!XYZ",
    "new_password2": "abc123!XYZ"
}
