# Generated by Django 5.1.4 on 2025-01-11 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_project',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='name')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellblade_core.project')),
            ],
            options={
                'db_table': 'core_section',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='due date')),
                ('recurrence', models.IntegerField(choices=[(-1, 'Never'), (0, 'Every day'), (1, 'Every week')], default=-1, verbose_name='recurring frequency')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellblade_core.section')),
            ],
            options={
                'db_table': 'core_task',
            },
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_project_name'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_section_name'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('section', 'name'), name='unique_task_name'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('recurrence', -1), ('due_at__isnull', False), _connector='OR'), name='task_recurrence_requires_due_date', violation_error_message='The due date must be set if the task is recurring.'),
        ),
    ]
