# Generated by Django 5.1.4 on 2025-01-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellblade_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='task_recurrence_requires_due_date',
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('recurrence', -1), ('due_at__isnull', False), _connector='OR'), name='task_recurrence_requires_due_date'),
        ),
    ]
