# Generated by Django 5.1.4 on 2025-01-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellblade_core', '0002_remove_task_task_recurrence_requires_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='task_recurrence_requires_due_date',
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('recurrence', -1), ('due_at__isnull', False), _connector='OR'), name='task_recurrence_requires_due_date', violation_error_message='The due date must be set if the task is recurring.'),
        ),
    ]
