# Generated by Django 5.1.4 on 2025-01-11 15:32

import spellblade_auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellblade_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text="Username must be between 1 and 20 characters, and can only contain letters, numbers, hyphens, and periods. It can't start with a number or a special character, and it can't end with a special character.", max_length=20, unique=True, validators=[spellblade_auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
