# Generated by Django 5.1.4 on 2025-01-12 17:45

import django.contrib.auth.models
import django.db.models.deletion
import spellblade_auth.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('spellblade_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text="Your username must be at most 150 characters, and can only contain letters, numbers, hyphens, and periods. It can't begin with a number or a special character, end with a special character, or contain consecutive special characters.", max_length=150, unique=True, validators=[spellblade_auth.models.UsernameUnicodeValidator()], verbose_name='username'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
        migrations.CreateModel(
            name='OutstandingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'outstanding token',
                'verbose_name_plural': 'outstanding tokens',
                'db_table': 'auth_outstanding_token',
            },
        ),
    ]
