# Generated by Django 5.1.4 on 2025-01-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellblade_auth', '0002_group_alter_user_username_alter_user_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outstandingtoken',
            options={'verbose_name': 'Outstanding Token', 'verbose_name_plural': 'Outstanding Tokens'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddIndex(
            model_name='outstandingtoken',
            index=models.Index(fields=['token'], name='auth_outsta_token_657e49_idx'),
        ),
    ]
