EMAIL_REQUIRED = 'EMAIL_REQUIRED'
EMAIL_TYPE_MISMATCH = 'EMAIL_TYPE_MISMATCH'
EMAIL_LENGTH_MISMATCH = 'EMAIL_LENGTH_MISMATCH'
INVALID_EMAIL_FORMAT = 'INVALID_EMAIL_FORMAT'

PASSWORD_REQUIRED = 'PASSWORD_REQUIRED'
PASSWORD_TYPE_MISMATCH = 'PASSWORD_TYPE_MISMATCH'
PASSWORD1_REQUIRED = 'PASSWORD1_REQUIRED'
PASSWORD2_REQUIRED = 'PASSWORD2_REQUIRED'
PASSWORD1_TYPE_MISMATCH = 'PASSWORD1_TYPE_MISMATCH'
PASSWORD2_TYPE_MISMATCH = 'PASSWORD2_TYPE_MISMATCH'
PASSWORDS_MISMATCH = 'PASSWORDS_MISMATCH'
PASSWORD_TOO_WEAK = 'PASSWORD_TOO_WEAK'

FIRST_NAME_REQUIRED = 'FIRST_NAME_REQUIRED'
FIRST_NAME_TYPE_MISMATCH = 'FIRST_NAME_TYPE_MISMATCH'
FIRST_NAME_LENGTH_MISMATCH = 'FIRST_NAME_LENGTH_MISMATCH'

LAST_NAME_REQUIRED = 'LAST_NAME_REQUIRED'
LAST_NAME_TYPE_MISMATCH = 'LAST_NAME_TYPE_MISMATCH'
LAST_NAME_LENGTH_MISMATCH = 'LAST_NAME_LENGTH_MISMATCH'

INCORRECT_PASSWORD = 'INCORRECT_PASSWORD'

REFRESH_TOKEN_REQUIRED = 'REFRESH_TOKEN_REQUIRED'
INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN'

ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE'
ACCOUNT_ALREADY_EXISTS = 'ACCOUNT_ALREADY_EXISTS'
ACCOUNT_DOES_NOT_EXIST = 'ACCOUNT_DOES_NOT_EXIST'

UNEXPECTED_ERROR = 'UNEXPECTED_ERROR'
